### ISSUE TITLE
Able to see Post with 0 meals in food availability page. Also Post with expired "food availability till" can also be seen on the page. Please see the SS.  

### ISSUE THREAD

**Issue by VISHDIVGAU** [gcivil-nyu-org/Team_Team5_CS-GY-6063-Fall2021#223]
![team5issue1.png](https://images.zenhubusercontent.com/614e108cc19f8ac004baa3cc/682280ef-d3ba-44d7-93f0-3885bfda10c3)

**Comment by HenryTseTse** [comment]
This is actually not a bug, we are allowing restaurants to update their food availability as they are giving away meals. They should be allowed to show that there are no more meals for the day, since there is currently no delete function. However, there might be a better way to show that there is no meals left, thanks for the feedback

**Comment by VISHDIVGAU** [comment]
I understand your logic. But as I pointed out, post with expired "food
availability till" with zero meals can also be seen in food availablity
page... I think you can have some sort of validation on "number of meals"
and " food availability till" attributes. This can help you display most
updated information on this page. Thank you.
